services:
  - type: static
    name: cherepanovstudio
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_TELEGRAM_USERNAME
        sync: false
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
